stages:
  - build
  - test
  - publish

build:
  stage: build
  tags: 
    - csc340
  only:
    - main
  script:
    - cd Team5
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish --configuration Release --output ../publish/
  artifacts:
    paths:
      - ./publish/*.*
    expire_in: 1 week
  
test:
  stage: test
  tags: 
    - csc340
  script:
    - dotnet test --logger:"junit;LogFilePath=..\test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./*test-result.xml
    reports:
      junit:
        - ./*test-result.xml

publish:
  stage: publish
  tags:
    - csc340
  only:
    - main
  script:
    - dotnet publish --configuration Release --output ./publish
  artifacts:
    paths:
      - ./publish/*.*
    expire_in: 1 week